#!/bin/bash
set -euo pipefail
app=$(basename "$0")
img='copilot-cli'

cfg_dir="$HOME/.config/copilot-cli"
allowed_paths="$cfg_dir/allowed_paths"

mkdir -p "$cfg_dir"
[ -f "$allowed_paths" ] || cat <<EOF > "$allowed_paths"
^/tmp/tmp\\.
^$HOME/prjs/
^$HOME/ext_prjs/
^$HOME/tmp/
EOF

function ensure_allowed # <1:dir>
{
  grep -q -f "$allowed_paths" <<< "$1" && return 0
  return 1
}

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--user="$(id -u):$(id -g)")
flags+=(--name="$img-$USER-$$")

flags+=(--env HOME=/tmp)
flags+=(--env GITHUB_TOKEN)

if ensure_allowed "$PWD"
then
  echo "$app: mounting $PWD in R/W mode"
  flags+=(--volume "$PWD:$PWD:rw")
  flags+=(--workdir "$PWD")
else
  echo "$app: directory $PWD is not whitelisted - NOT MOUNTING"
  flags+=(--workdir /tmp)
fi

flags+=("$img")

exec docker run "${flags[@]}" "$@"
