#!/bin/bash
APP=$(basename "$0")

function log
{
  echo   "$(date): $APP: $*"
  logger          "$APP: $*"
}


function monitor_inactivity
{
  while sleep 10
  do
    [ "$(xprintidle)" -lt "$((30*1000))" ] && continue
    xset dpms force off
    sleep 20
  done
}


#
# main
#

monitor_inactivity &
MONITOR=$!

log "locking screen"
xtrlock -b
log "screen unlocked"

kill "$MONITOR"
log "monitor script stopped"
