#!/bin/bash
set -eu -o pipefail

app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")

if [ $# -ne 2 ]
then
  echo "$0 <retraction_start> <retraction_delta>" >&2
  exit 2
fi
retraction_start=$1
retraction_delta=$2
shift 2

cd "$app_dir"
segment_h=$(cat retraction_column_pla.scad | grep '^segment_h *=' | sed 's/.*= *//' | tr -d ';')

for f in $(find build -name 'retraction_column_*.gcode')
do
  grep -q ".*_dynamic.gcode$" <<< "$f" && continue
  layer_h=$(cat "$f" | grep '^; layer_height *= *' | sed 's/.*= *//' | tr -d ';')
  out="${f%.gcode}_dynamic.gcode"
  echo "$app: processing $f -> $out"
  ( set -x ; ./modify_retract_lengths "$layer_h" "$segment_h" "$retraction_start" "$retraction_delta" "$f" "$out" )
done
