margin   = 1.05;
hull     = 2;
spacing  = 2;
diameter = 14.5;
radius   = diameter/2;
sizeOX   = 2*hull + 4*diameter + 3*spacing;
sizeOY   = 2*hull + 48.5+2;
sizeOZ   = 2*hull + diameter;
screwDiameter = 3;
