#!/bin/bash
set -euo pipefail
app=$(basename "$0")
img='opencode-cli'
net='ollama-net'

cfg_dir="$HOME/.config/opencode-cli"
home_dir="$cfg_dir/home"
allowed_paths="$cfg_dir/allowed_paths"

mkdir -p "$cfg_dir"
mkdir -p "$home_dir"
[ -f "$allowed_paths" ] || cat <<EOF > "$allowed_paths"
^/tmp/tmp\\.
EOF

function ensure_allowed # <1:dir>
{
  grep -q -f "$allowed_paths" <<< "$(readlink -e "$1")" && return 0
  return 1
}

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--user="$(id -u):$(id -g)")
flags+=(--name="$img-$USER-$$")

flags+=(--env          HOME=/home/opencode)
flags+=(--volume "$home_dir:/home/opencode")

flags+=(--network="$net")

if ensure_allowed "$PWD"
then
  echo "$app: mounting $PWD in R/W mode"
  flags+=(--volume "$PWD:$PWD:rw")
  flags+=(--workdir "$PWD")
else
  echo "$app: directory $PWD is not whitelisted - NOT MOUNTING"
  flags+=(--workdir /tmp)
fi

flags+=("$img")

exec docker run "${flags[@]}" "$@"
