#!/bin/bash
set -euo pipefail
app=$(basename "$0")
img='opencode-cli'
net='ollama-net'

cfg_dir="$HOME/.config/opencode-cli"
home_dir="$cfg_dir/home"
allowed_paths="$cfg_dir/allowed_paths"

mkdir -p "$cfg_dir"
mkdir -p "$home_dir"
[ -f "$allowed_paths" ] || cat <<EOF > "$allowed_paths"
^/tmp/tmp\\.
EOF

mkdir -p "$home_dir/.config/opencode"

function ensure_allowed # <1:dir>
{
  grep -q -f "$allowed_paths" <<< "$(readlink -e "$1")/" && return 0
  return 1
}

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--user="$(id -u):$(id -g)")
flags+=(--name="$img-$USER-$$")

flags+=(--env          HOME=/home/opencode)
flags+=(--volume "$home_dir:/home/opencode")

if [ "${LLM_ALLOW_INTERNET:-0}" = "1" ] || [ "${LLM_ALLOW_INTERNET:-false}" = "true" ]
then
  echo "$app: harness is allowed internet access, per request"
else
  if docker inspect "$net" > /dev/null 2>&1
  then
    flags+=(--network="$net")
  else
    echo "$app: neither internet is allowed nor Ollama is found - disabling all networking" >&2
    flags+=(--network=none)
  fi
fi

if ensure_allowed "$PWD"
then
  echo "$app: mounting $PWD in R/W mode"
  flags+=(--volume "$PWD:$PWD:rw")
  flags+=(--workdir "$PWD")
else
  echo "$app: directory $PWD is not whitelisted - NOT MOUNTING"
  flags+=(--workdir /tmp)
fi

flags+=("$img")

exec docker run "${flags[@]}" "$@"
