#!/bin/bash
set -eu -o pipefail
app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")
img='steam_image'

cd "$app_dir"
data="$PWD/data"
mkdir -p "$data"

function image_rebuild_needed
{
  # image does not exist?
  if ! docker image ls | grep "$img"
  then
    return 0
  fi
  # image is too old?
  local created_ts=$(docker inspect "$img" | jq -r '.[0].Created' | xargs date +%s -d)
  local now_ts=$(date +%s)
  if [ "$(($now_ts-$created_ts))" -gt "$((31*24*3600))" ]
  then
    return 0
  fi
  return 1
}

build_flags=()
build_flags+=(--tag "$img")
build_flags+=(--build-arg "UID=$(id -u)")
build_flags+=(--build-arg "GID=$(id -g)")
if image_rebuild_needed
then
  date > "img/last-dist-upgrade.ts"
fi
time docker build "${build_flags[@]}" img/

run_flags=()

# common stuff
run_flags+=(--interactive)
run_flags+=(--tty)
run_flags+=(--rm)
run_flags+=(--name "steam_$USER")

# proer signals passing
run_flags+=(--init)

# having too many possible descriptors cause issues with some applications
run_flags+=(--ulimit "nofile=1024")

# stable needed to prevent re-authorization on each startup
run_flags+=(--hostname "steam-container")

# pulseaudio
run_flags+=(--volume "/run/user/$UID/pulse:/run/user/$UID/pulse")

# GPU
run_flags+=(--device  /dev/dri)
run_flags+=(--device  /dev/kfd)
#run_flags+=(--volume "/dev/dri:/dev/dri")
#run_flags+=(--volume "/dev/kfd:/dev/kfd")
run_flags+=(--device  /dev/dri/card0)
run_flags+=(--device  /dev/dri/renderD128)
run_flags+=(--volume "/dev/shm:/dev/shm")
#run_flags+=(--runtime "amd")
#run_flags+=(--env AMD_VISIBLE_DEVICES=all)
#run_flags+=(--security-opt seccomp=unconfined)
run_flags+=(--group-add "$(getent group video  | cut -d: -f3)")
run_flags+=(--group-add "$(getent group render | cut -d: -f3)")

# perms mapped to local user to make things work
run_flags+=(--user "$(id -u):$(id -g)")
run_flags+=(--group-add "$(getent group audio | cut -d: -f3)")

if [ "${WAYLAND_DISPLAY:-}" != "" ]
then
  echo "$app: forwarding Wayland"
  run_flags+=(--env WAYLAND_DISPLAY)
  run_flags+=(--env XDG_RUNTIME_DIR)
  run_flags+=(--env XDG_SESSION_TYPE)
  run_flags+=(--volume "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY")
  run_flags+=(--volume "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR")
  # X11 compatibility
  run_flags+=(--env DISPLAY)
  run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
  run_flags+=(--env QT_X11_NO_MITSHM=1)
else
  if [ "${DISPLAY:-}" != "" ]
  then
    echo "$app: farwarding X11"
    run_flags+=(--env DISPLAY)
    run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
    run_flags+=(--env QT_X11_NO_MITSHM=1)
    #xhost "+si:localuser:$USER"
  else
    echo "$app: neither Wayland nor X11 found - aborting" >&2
    exit 2
  fi
fi

# home dir with the actual content
run_flags+=(--volume "$data:/home/user")
run_flags+=(--env "HOME=/home/user")
run_flags+=(--workdir "/home/user")

# make sure joystick is forwarded
run_flags+=(--group-add "$(getent group input | cut -d: -f3)")
for dev in $(find /dev/input/* /dev/hidraw* -type c)
do
  run_flags+=(--device "$dev")
done

# making bwrap happy
run_flags+=(--cap-add SYS_ADMIN)
run_flags+=(--security-opt apparmor=unconfined)
run_flags+=(--security-opt seccomp=unconfined)

steam_flags=()

echo "$0: if CEF fails again, edit ~/data_misc/steam/data/.local/share/Steam/ubuntu12_64/steamwebhelper.sh"
steam_flags+=(--disable-gpu-sandbox)
steam_flags+=(-no-browser)

set -x
exec docker run "${run_flags[@]}" "$img" steam "${steam_flags[@]}" "$@"
