#!/bin/bash
set -euo pipefail
app=$(basename "$0")
ver="v2026.8.31"
img="nousresearch/hermes-agent:$ver"
net='ollama-net'

cfg_dir="$HOME/.config/hermes-agent"
home_dir="$cfg_dir/home"
data_dir="$cfg_dir/data"
allowed_paths="$cfg_dir/allowed_paths"

mkdir -p "$cfg_dir"
mkdir -p "$home_dir"
[ -f "$allowed_paths" ] || cat <<EOF > "$allowed_paths"
^/tmp/tmp\\.
EOF

function ensure_allowed # <1:dir>
{
  grep -q -f "$allowed_paths" <<< "$(readlink -e "$1")" && return 0
  return 1
}

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--name="hermes-agent-$USER-$$")

#flags+=(--user="$(id -u):$(id -g)")
flags+=(--env HERMES_UID="$(id -u)")
flags+=(--env HERMES_GID="$(id -g)")

flags+=(--env         HOME="/home/hermes")
flags+=(--volume "$home_dir:/home/hermes")
flags+=(--volume "$data_dir:/opt/data")

flags+=(--network="$net")

if ensure_allowed "$PWD"
then
  echo "$app: mounting $PWD in R/W mode"
  flags+=(--volume "$PWD:$PWD:rw")
  flags+=(--workdir "$PWD")
else
  echo "$app: directory $PWD is not whitelisted - NOT MOUNTING"
  flags+=(--workdir /tmp)
fi

flags+=("$img")

exec docker run "${flags[@]}" "$@"
