#!/bin/bash

# http://www.comics.com/comics/pearls/archive/pearls-20080514.html
HOST="http://www.comics.com"
DATE="`date +%Y%m%d`"
DST_DIR="."
[ "$1" ] && DST_DIR="$1"
[ "$2" ] && DATE="$2"
DST_DIR="`readlink -f "$DST_DIR"`"
WWW="$HOST/comics/pearls/archive/pearls-$DATE.html"
TMP_DIR="`mktemp -d`"

cd "$TMP_DIR"    || exit $?
wget -q "$WWW"   || exit $?
# /comics/pearls/archive/images/pearls2004890280514.gif
IMG="`grep '"/comics/pearls/archive/images/pearls.*"' pearls-*.html | sed 's:.*"/\(comics/pearls/archive/images/pearls[^"]\+\)".*:\1:'`"
STRIP="$HOST/$IMG"
wget -q "$STRIP" || exit $?
IMG_FILE="`sed 's:.*/::' <<< "$IMG"`"
cp "$IMG_FILE" "$DST_DIR/pearls_before_swine_$DATE.gif" || exit $?

# cleanup
cd "$TMP_DIR"                || exit $?
rm pearls-*.html "$IMG_FILE" || exit $?
rmdir "$TMP_DIR"             || exit $?

exit 0
