#!/bin/bash

# http://ars.userfriendly.org/cartoons/?id=20080513
HOST="http://ars.userfriendly.org"
DATE="`date +%Y%m%d`"
DST_DIR="."
[ "$1" ] && DST_DIR="$1"
[ "$2" ] && DATE="$2"
DST_DIR="`readlink -f "$DST_DIR"`"
WWW="$HOST/cartoons/?id=$DATE"
TMP_DIR="`mktemp -d`"

cd "$TMP_DIR"    || exit $?
wget -q "$WWW"   || exit $?
# /cartoons/archives/08may/uf011514.gif
IMG="`grep '/cartoons/archives/[^\.]\+.gif' index.* | sed 's:.*src="\([^"]\+\)".*:\1:'`"
STRIP="$IMG"
wget -q "$STRIP" || exit $?
IMG_FILE="`sed 's:.*/::' <<< "$IMG"`"
cp "$IMG_FILE" "$DST_DIR/user_friendly_$DATE.gif" || exit $?

# cleanup
cd "$TMP_DIR"          || exit $?
rm index.* "$IMG_FILE" || exit $?
rmdir "$TMP_DIR"       || exit $?

exit 0
