#!/usr/bin/env python3
# taken from: https://forum.freecadweb.org/viewtopic.php?t=41277
import sys
sys.path.append("/usr/lib/freecad/lib")
import FreeCAD
import Part

if len(sys.argv) != 1+2:
    sys.stderr.write("{} <input.step> <output.stl>\n".format(sys.argv[0]))
    sys.exit(2)

s = Part.Shape()
s.read(sys.argv[1])
s.exportStl(sys.argv[2], 2.5)
