#!/usr/bin/env python3

steps = 20

def gamma(n):
  gamma_correction = 1.3
  v = ( n / steps ) ** gamma_correction
  return v * 100

print("#pragma once")
print("#include <stdint.h>")
print("#include \"config.hpp\"")
print("")
print("inline uint8_t step2brightness(uint8_t const step_current)")
print("{")
print(f"  static_assert( c_gamma_steps == {steps}, \"align number of steps across code\" );")
print("  switch(step_current)")
print("  {")
for n in range(0, steps+1):
  gc = gamma(n)
  print(f"      case {n:>2}: return static_cast<uint8_t>({gc});")
print("  }")
print("  return 0; // this code is never reached")
print("}")
