#!/bin/bash
set -euo pipefail
app=$(basename "$0")

# see: https://github.com/yt-dlp/yt-dlp/releases/
readonly version="2026.07.04"
readonly checksum="495be29ff4d9d4e9be7eabdfef225221e5d5282e77f2f505abc6dca80349f3fd"
readonly img='yt-dlp-docker'

if [ $# -lt 2 ]
then
  echo "$app </output/dir/to/be/mounted> [yt-dlp-flags...]" >&2
  exit 2
fi

[ -d "$1" ] || { echo "$app: output dir '$1' does not exist" >&2 ; exit 3 ; }
readonly output_dir=$(readlink -e "$1")
shift 1

docker build -t "$img" - <<EOF
FROM debian:13
RUN apt-get update && apt-get dist-upgrade -y
RUN apt-get install -y python3 wget
RUN apt-get install -y ffmpeg
RUN apt-get install -y nodejs
RUN wget -O /usr/local/bin/yt-dlp 'https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp' && \
    echo "$checksum  /usr/local/bin/yt-dlp" > /tmp/checksums && \
    sha256sum -c /tmp/checksums && \
    chmod 755 /usr/local/bin/yt-dlp
RUN apt-get update && apt-get dist-upgrade -y # refresh deps, if needed
ENTRYPOINT [ "yt-dlp", "--js-runtimes", "node" ]
EOF

flags=()
stty > /dev/null 2>&1 && flags+=(-i)
flags+=(-t)
flags+=(--rm)
flags+=(-u "$(id -u):$(id -g)")
flags+=(--name "yt-dlp_${USER:-crontab}_$$")

flags+=(-v "$output_dir:$output_dir")
flags+=(-w "$output_dir")

flags+=("$img")

set -x
exec docker run "${flags[@]}" "$@"
