# bambulab's printers tend to heavily under-extrude for a nicer part look.
# therefor most of the models designed and printed on these, have too narrow tolerances to be printed with 100% (aka: normal) extrusion rates.
extrusion_multiplier = 0.94
