#!/bin/bash
set -eu -o pipefail
app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")
img='cubicsdr'
home=$app_dir/.home

mkdir -p "$home"
echo '*' > "$home/.gitignore"

build_flags=()
build_flags+=(--tag "$img")
time docker build "${build_flags[@]}" docker/

run_flags=()

# common stuff
run_flags+=(--interactive)
run_flags+=(--tty)
run_flags+=(--rm)
run_flags+=(--name "${img}_$USER")

# proer signals passing
run_flags+=(--init)

# having too many possible descriptors cause issues with some applications
run_flags+=(--ulimit "nofile=1024")

# stable needed to prevent re-authorization on each startup
run_flags+=(--hostname "cubicsdr")

# pulseaudio / pipewire
run_flags+=(--volume "/run/user/$UID/pulse:/run/user/$UID/pulse")
run_flags+=(--group-add "$(getent group audio | cut -d: -f3)")

# perms mapped to local user to make things work
run_flags+=(--user "$(id -u):$(id -g)")

if [ "${WAYLAND_DISPLAY:-}" != "" ]
then
  echo "$app: forwarding Wayland"
  run_flags+=(--env WAYLAND_DISPLAY)
  run_flags+=(--env XDG_RUNTIME_DIR)
  run_flags+=(--env XDG_SESSION_TYPE)
  run_flags+=(--volume "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY")
  run_flags+=(--volume "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR")
  # X11 compatibility
  run_flags+=(--env DISPLAY)
  run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
  run_flags+=(--env QT_X11_NO_MITSHM=1)
  run_flags+=(--env XDG_SESSION_TYPE)
else
  if [ "${DISPLAY:-}" != "" ]
  then
    echo "$app: farwarding X11"
    run_flags+=(--env DISPLAY)
    run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
    run_flags+=(--env QT_X11_NO_MITSHM=1)
    xhost "+si:localuser:$USER"
  else
    echo "$app: neither Wayland nor X11 found - aborting" >&2
    exit 2
  fi
fi

# forward all USB devices
read bus_id dev_id <<< $(lsusb | grep RTL | awk '{ print $2, $4 }' | tr -d :)
dev="/dev/bus/usb/$bus_id/$dev_id"
run_flags+=(--device "$dev")
run_flags+=(--group-add "$(stat --format %g "$dev")")

# home dir with the actual content
run_flags+=(--volume "$home:/home/user")
run_flags+=(--env "HOME=/home/user")
run_flags+=(--workdir "/home/user")

set -x
exec docker run "${run_flags[@]}" "$img" CubicSDR "$@"
