#!/bin/bash
set -e

DOWNLOADS_DIR="$HOME/downloads"
NEW_DOWNLOAD="$TR_TORRENT_DIR/$TR_TORRENT_NAME"

{
  date
  echo "command line: $0 $*"
  echo "TR_APP_VERSION    = $TR_APP_VERSION"
  echo "TR_TIME_LOCALTIME = $TR_TIME_LOCALTIME"
  echo "TR_TORRENT_DIR    = $TR_TORRENT_DIR"
  echo "TR_TORRENT_HASH   = $TR_TORRENT_HASH"
  echo "TR_TORRENT_ID     = $TR_TORRENT_ID"
  echo "TR_TORRENT_NAME   = $TR_TORRENT_NAME"

  time mv -v "$NEW_DOWNLOAD" "$DOWNLOADS_DIR/"

  date
  echo "done"
} 2>&1 | tee "$DOWNLOADS_DIR/${TR_TORRENT_NAME}.transmission-log"
