#!/bin/bash
#
# source:
# https://baszerr.eu/doku.php?id=blog:2022:01:30:2022-01-30_-_missing_user_in_docker_image
#
set -eu -o pipefail

if [ $# -eq 0 ]
then
  exec "$0" "bash"
fi

# workaround for missing user account in /etc/passwd - some tools can't handle it...
read R_UID R_GID <<< "$(echo "$REAL_USER" | tr ':' ' ')"
groupadd -g "$R_GID" "user"
useradd -g "$R_GID" -u "$R_UID" -s "/bin/bash" "user"

export USER="user"
export HOME="/home/$USER"

mkdir -p "$HOME"
chown "$R_UID:$R_GID" "$HOME"

exec setpriv --reuid "user" --regid "user" --init-groups "$@"
