#!/bin/bash
set -euo pipefail
app=$(basename "$0")
img='ollama'
net='ollama-net'
name_server="$img-$USER"

function cleanup
{
  local readonly net_users="$(docker network inspect "$net" 2>/dev/null | jq '.[0].Containers | length')"
  [ "$net_users" -gt 0 ] || docker network rm "$net"
}
trap cleanup EXIT


cache_dir="$HOME/.cache/ollama"
mkdir -p "$cache_dir"

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--user="$(id -u):$(id -g)")

flags+=(--env           HOME=/home/ollama)
flags+=(--volume "$cache_dir:/home/ollama")

flags+=(--network="$net")
flags+=(--env OLLAMA_HOST="$name_server:11434")

# 1st container is assumed to be server - rest are the clients, with PID-based names
if docker container inspect "$name_server" > /dev/null 2>&1
then
  flags+=(--name "$name_server-client-$$")
else
  docker network create "$net"
  flags+=(--name "$name_server")
fi

if [ -e /dev/kfd ] && [ -e /dev/dri ]
then
  flags+=(--device=/dev/kfd)
  flags+=(--device=/dev/dri)
  for g in render video
  do
    flags+=(--group-add "$(getent group "$g" | cut -d: -f3)")
  done
fi

flags+=(--read-only)
flags+=("$img")

docker run "${flags[@]}" "$@"
