#!/bin/bash
set -euo pipefail
app=$(basename "$0")
img='ollama'
net='ollama-net'
name_server="$img-$USER"
name="$name_server"

# 1st container is assumed to be server - rest are the clients, with PID-based names
docker container inspect "$name" > /dev/null 2>&1 && name="$name-$$" || true

# create a network, if does not exist yet
docker network inspect "$net" > /dev/null 2>&1 || docker network create "$net"

cache_dir="$HOME/.cache/ollama"
mkdir -p "$cache_dir"

flags=()

stty -a > /dev/null 2>&1 && flags+=(--interactive)
flags+=(--tty)
flags+=(--rm)
flags+=(--init)
flags+=(--user="$(id -u):$(id -g)")
flags+=(--name="$name")

flags+=(--env           HOME=/home/ollama)
flags+=(--volume "$cache_dir:/home/ollama")

flags+=(--network="$net")
flags+=(--env OLLAMA_HOST="$name_server:11434")

flags+=(--read-only)
flags+=("$img")

exec docker run "${flags[@]}" "$@"
