#!/bin/bash

# script sets reasonable permisions for files (644) and dirs (755).

if [ "${*}" = "--help" ] || [ "$#" -lt 1 ]
then
 echo "${0} [dir1] [dir2] ... [dirN]" >&2
 exit 1
fi

dir="$1"
while shift
do
  find "$dir" -type d -exec chmod 755 {} \; || exit $?
  find "$dir" -type f -exec chmod 644 {} \; || exit $?
  dir="$1"
done
exit 0
