#!/bin/bash
set -eu -o pipefail
readonly app=$(basename "$0")
readonly app_dir=$(dirname "$(readlink -e "$0")")
readonly app_name=$(basename "$(dirname "$0")")
readonly img="game_${app_name}"

cd "$app_dir"
readonly data="$PWD/data"
mkdir -p "$data"

build_flags=()
build_flags+=(--tag "$img")
build_flags+=(--build-arg "UID=$(id -u)")
build_flags+=(--build-arg "GID=$(id -g)")
time docker build "${build_flags[@]}" img/

run_flags=()

# common stuff
run_flags+=(--interactive)
run_flags+=(--tty)
run_flags+=(--rm)
run_flags+=(--name "${img}_$USER")

# proer signals passing
run_flags+=(--init)

# having too many possible descriptors cause issues with some applications
run_flags+=(--ulimit "nofile=1024")

# stable needed to prevent re-authorization on each startup
run_flags+=(--hostname "gaming-container")

# pulseaudio
run_flags+=(--volume "/run/user/$UID/pulse:/run/user/$UID/pulse")

# GPU
run_flags+=(--device  /dev/dri)
run_flags+=(--device  /dev/kfd)
#run_flags+=(--volume "/dev/dri:/dev/dri")
#run_flags+=(--volume "/dev/kfd:/dev/kfd")
run_flags+=(--device  /dev/dri/card0)
run_flags+=(--device  /dev/dri/renderD128)
run_flags+=(--volume "/dev/shm:/dev/shm")
#run_flags+=(--runtime "amd")
#run_flags+=(--env AMD_VISIBLE_DEVICES=all)
#run_flags+=(--security-opt seccomp=unconfined)
run_flags+=(--group-add "$(getent group video  | cut -d: -f3)")
run_flags+=(--group-add "$(getent group render | cut -d: -f3)")

# perms mapped to local user to make things work
run_flags+=(--user "$(id -u):$(id -g)")
run_flags+=(--group-add "$(getent group audio | cut -d: -f3)")

if [ "${WAYLAND_DISPLAY:-}" != "" ]
then
  echo "$app: forwarding Wayland"
  run_flags+=(--env WAYLAND_DISPLAY)
  run_flags+=(--env XDG_RUNTIME_DIR)
  run_flags+=(--env XDG_SESSION_TYPE)
  run_flags+=(--volume "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY")
  run_flags+=(--volume "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR")
  # X11 compatibility
  run_flags+=(--env DISPLAY)
  run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
  run_flags+=(--env QT_X11_NO_MITSHM=1)
  run_flags+=(--env XDG_SESSION_TYPE)
else
  if [ "${DISPLAY:-}" != "" ]
  then
    echo "$app: farwarding X11"
    run_flags+=(--env DISPLAY)
    run_flags+=(--volume "/tmp/.X11-unix:/tmp/.X11-unix:ro")
    run_flags+=(--env QT_X11_NO_MITSHM=1)
    xhost "+si:localuser:$USER"
  else
    echo "$app: neither Wayland nor X11 found - aborting" >&2
    exit 2
  fi
fi

# home dir with the actual content
run_flags+=(--volume "$data:/home/user")
run_flags+=(--env "HOME=/home/user")
run_flags+=(--workdir "/home/user")

# make sure joystick is forwarded
run_flags+=(--group-add "$(getent group input | cut -d: -f3)")
for dev in /dev/input/{event,mice,mouse}* /dev/hidraw*
do
  run_flags+=(--device "$dev")
done
run_flags+=(--volume /dev/input/by-id:/dev/input/by-id)
run_flags+=(--volume /dev/input/by-path:/dev/input/by-path)

# making bwrap happy
#run_flags+=(--cap-add SYS_ADMIN)
#run_flags+=(--security-opt apparmor=unconfined)
#run_flags+=(--security-opt seccomp=unconfined)

# installers
run_flags+=(--volume ./installer:/mnt/installer:ro)

set -x
exec docker run "${run_flags[@]}" "$img" "$@"
